# Generated by Django 5.0.4 on 2025-04-18 17:15

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles', validators=[Petstagram.photos.validators.validate_file_size]),
        ),
    ]
