# Generated by Django 5.0.4 on 2025-05-20 20:28

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='', validators=[Petstagram.photos.validators.validate_file_size]),
        ),
    ]
